### ISSUE TITLE
CI with Coveralls

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify#3328]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Make use of `continue-on-error` to prevent future impact on `coveralls` maintenance.
The tools like `coveralls` should never be the blocker for CI.

It should be applied to the repo that using `coveralls` inside the organization.

### Motivation

Coveralls Maintenance.
https://status.coveralls.io/incidents/ppvnbpd172gy
https://status.coveralls.io/incidents/8zbjrwpb4frv

### Example

I have update this repo in below and it should be the example of other repo.
https://github.com/fastify/fastify/blob/36f4b67b5940d89d12f1eefc733bbd0d7f5e1afb/.github/workflows/ci.yml#L13-L71

It will allow the stage of `coverall` to fail and skip the collection stage if any of the `coveralls` step inside `test` fail.

**Comment by mcollina** [comment]
I would also say that we should remove coveralls from all repos that have enforced 100% code coverage.

**Comment by climba03003** [comment]
I am good with both remove it or keep it. 
But the important point is not blocking the CI.

**Comment by mcollina** [comment]
Yes, exactly

**Comment by sudhay23** [comment]
Hello, can I work on this if it's open for fixes? Can you please guide me with some more information about the same?

**Comment by Fdawgs** [comment]
> I am good with both remove it or keep it. 
> 
> But the important point is not blocking the CI.

Probably best to keep it across all to have a consistent CI config across the repos, but yeah stopping it from blocking is a good idea!

**Comment by climba03003** [comment]
Feel free to open PR for the fixing it in other repo.
I have add the comment on how it works.
```yaml
 jobs: 
   test: 
     runs-on: ${{ matrix.os }} 
     # output.COVERALLS is a variable to determine should we post to coveralls when all parallel test finish
     outputs: 
       COVERALLS: ${{ steps.coveralls-trigger.outputs.COVERALLS_TRIGGER }} 
  
     ...

     steps:   

     ...

       - name: Coveralls Parallel 
         id: coveralls-parallel 
         # allow this step to fail
         continue-on-error: true 
         uses: coverallsapp/github-action@master 
         with: 
           github-token: ${{ secrets.github_token }} 
           parallel: true 
           flag-name: run-${{ matrix.node-version }}-${{ matrix.os }} 
  
       # step to determine if the next job should run
       # failed one job means we should not run the next job
       - name: Should Trigger coverallsapp/github-action@master 
         id: coveralls-trigger 
         # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context 
         # when continue-on-error failed, outcome is failure and conclusion is success 
         if: steps.coveralls-parallel.conclusion == 'success' && steps.coveralls-parallel.outcome != 'success' 
         run: | 
           echo "::set-output name=COVERALLS_TRIGGER::failure" 
            
  
   coverage: 
     needs: test 
     runs-on: ubuntu-latest 
     # check if we should run this job
     if: needs.test.outputs.COVERALLS != 'failure' 
     steps: 
       - name: Coveralls Finished 
         uses: coverallsapp/github-action@master 
         with: 
           github-token: ${{ secrets.GITHUB_TOKEN }} 
           parallel-finished: true 
```
