### ISSUE TITLE
[4.0.1] Cannot find module fast-json-stringify/serializer

### ISSUE THREAD

**Issue by DRoet** [fastify/fastify#3998]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.0.0

### Stopped working in version

4.0.1

### Node.js version

18.3.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Docker

### 💥 Regression Report

following error when starting my application:

```
node:internal/modules/cjs/loader:939
   const err = new Error(message);
               ^
 
 Error: Cannot find module 'fast-json-stringify/serializer'
 Require stack:
 - /app/node_modules/fastify/lib/error-serializer.js
 - /app/node_modules/fastify/lib/error-handler.js
 - /app/node_modules/fastify/lib/reply.js
 - /app/node_modules/fastify/fastify.js
     at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
     at Module._load (node:internal/modules/cjs/loader:780:27)
     at Module.require (node:internal/modules/cjs/loader:1005:19)
     at require (node:internal/modules/cjs/helpers:102:18)
     at Object.<anonymous> (/app/node_modules/fastify/lib/error-serializer.js:6:20)
     at Module._compile (node:internal/modules/cjs/loader:1105:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
     at Module.load (node:internal/modules/cjs/loader:981:32)
     at Module._load (node:internal/modules/cjs/loader:827:12)
     at Module.require (node:internal/modules/cjs/loader:1005:19) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
     '/app/node_modules/fastify/lib/error-serializer.js',
     '/app/node_modules/fastify/lib/error-handler.js',
     '/app/node_modules/fastify/lib/reply.js',
     '/app/node_modules/fastify/fastify.js'
   ]
 }

```

### Steps to Reproduce

Use simple hello world:

```js
import Fastify from 'fastify'
const fastify = Fastify({
   logger: true,
})

fastify.get('/', async (request, reply) => {
   return { hello: 'world' }
})

await fastify.listen({ port: 3000 })
```

and start it using `node app.js`

**Comment by DRoet** [comment]
Hmm I am using yarn v3.2.1 and it seems as if it is not pulling version 4.1.0 of `fast-json-stringify` after upgrading my dependencies using `yarn upgrade-interactive`

```yml
"fast-json-stringify@npm:^4.0.0":
  version: 4.0.0
  resolution: "fast-json-stringify@npm:4.0.0"
  dependencies:
    ajv: ^8.10.0
    ajv-formats: ^2.1.1
    deepmerge: ^4.2.2
    fast-uri: ^2.0.0
    rfdc: ^1.2.0
    string-similarity: ^4.0.1
  checksum: be75cc7f87a8cf8623a135de5513aae80e39cdc4df7f9f3c735c686f77f501edd06fa8361026cd6be3628ac4e5ff2f5fe804a9ab11b9ffb828979965548b5af4
  languageName: node
  linkType: hard
```
