### ISSUE TITLE
ci: cache node_modules?

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify#4146]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

@mcollina, can you share anything you've done in https://twitter.com/matteocollina/status/1544259116453007360?s=20&t=Kn2qBy7knbQ5sWhYpa5Fjg please? Would it be of any benefit to the Fastify repos?

**Comment by mcollina** [comment]
Caching node_modules comes with a tradeoff: the use of a lock file.
In that specific case that was a really good compromise. I'm not really convinced it is for this module. PTAL:

```
jobs:
  setup-node_modules:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # We cache the internal npm cache so we can speed things up
          # in case the package-lock.json is new
          cache: 'npm'
      - name: Cache node modules
        # ..and node_modules too!
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          # We use the -cacheN- modifier to be able to clear the cache easily.
          # In cache it's needed, replace -cacheN- with -cacheN+1- throughout the file, etc.. 
          key: node_modules-cache1-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
      - name: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  run-test-one: # I had 8 of those.
    needs: setup-node_modules
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Load node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node_modules-cache1-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
        # no restore-keys here, so we only accept this exact version
    - name: Start docker containers for testing
      run: docker-compose up -d
    - name: Run test suite
      run: npm run test:one
```
