### ISSUE TITLE
Tests are failing, while npm run test 

### ISSUE THREAD

**Issue by pacostas** [fastify/fastify#5373]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

## Steps to reproduce
OS on virtual machine:
`Linux fedora 6.7.4-200.fc39.x86_64` 

Node version:
`20.11.1`

Steps:
1. git clone https://github.com/fastify/fastify.git
2. cd fastify
3. npm i
4. npm run test

Gives below 2 errors:

* error 1
```
 FAIL ​ test/async-await.test.js 81 OK 1s
  command: /home/costas/.nvm/versions/node/v20.11.1/bin/node
  args:
    - --allow-natives-syntax
    - test/async-await.test.js
  exitCode: null
  signal: SIGTERM

 FAIL ​ TAP
 ✖ test/async-await.test.js

  test: TAP
  env: {}
  file: test/async-await.test.js
  timeout: 30000
  command: /home/costas/.nvm/versions/node/v20.11.1/bin/node
  args:
    - --allow-natives-syntax
    - test/async-await.test.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/costas/Desktop/fastify
  exitCode: null
  signal: SIGTERM

 FAIL ​ test/hooks.on-listen.test.js 165 OK 523.559ms
  command: /home/costas/.nvm/versions/node/v20.11.1/bin/node
  args:
    - --allow-natives-syntax
    - test/hooks.on-listen.test.js
  exitCode: null
  signal: SIGTERM

 FAIL ​ TAP
 ✖ test/hooks.on-listen.test.js

  test: TAP
  env: {}
  file: test/hooks.on-listen.test.js
  timeout: 30000
  command: /home/costas/.nvm/versions/node/v20.11.1/bin/node
  args:
    - --allow-natives-syntax
    - test/hooks.on-listen.test.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/costas/Desktop/fastify
  exitCode: null
  signal: SIGTERM

 FAIL ​ test/internals/reply.test.js 346 OK 2s
  command: /home/costas/.nvm/versions/node/v20.11.1/bin/node
  args:
    - --allow-natives-syntax
    - test/internals/reply.test.js
  exitCode: null
  signal: SIGTERM

 FAIL ​ TAP
 ✖ test/internals/reply.test.js

  test: TAP
  env: {}
  file: test/internals/reply.test.js
  timeout: 30000
  command: /home/costas/.nvm/versions/node/v20.11.1/bin/node
  args:
    - --allow-natives-syntax
    - test/internals/reply.test.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/costas/Desktop/fastify
  exitCode: null
  signal: SIGTERM

```
* error 2
```
 FAIL ​ test/hooks.on-listen.test.js 165 OK 523.559ms
  command: /home/costas/.nvm/versions/node/v20.11.1/bin/node
  args:
    - --allow-natives-syntax
    - test/hooks.on-listen.test.js
  exitCode: null
  signal: SIGTERM

 FAIL ​ test/internals/reply.test.js 346 OK 2s
  command: /home/costas/.nvm/versions/node/v20.11.1/bin/node
  args:
    - --allow-natives-syntax
    - test/internals/reply.test.js
  exitCode: null
  signal: SIGTERM

```
