### ISSUE TITLE
Automate plugins release and rotate keys automatically

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify#5984]
Hello folks!

I've been talking with @mcollina to find some areas of security where I could help fastify again. He told me it's a very time-consuming task to rotate 50+ plugins npm token keys every year and if we find a way to automate most of this stuff, it would make package maintenance a lot easier.

I have also talked with @ulisesgascon from Express team and it seems they will be working on something similar pretty soon, so why not a collaborative space so we could create something more universal?

That said, I'm opening this issue so you could give me some pain points you all suffer in terms of security nowadays and I can find some gaps where I could fill some part of my time. 

* Automate plugin release (with provenance) and a token rotation script.
* ...

Any more ideas?

**Comment by mcollina** [comment]
cc @Eomm

**Comment by RafaelGSS** [comment]
We can now use this https://docs.npmjs.com/trusted-publishers

**Comment by mcollina** [comment]
I just tested this and it works great.

What could be a rollout plan?

**Comment by UlisesGascon** [comment]
Seems like @wesleytodd did a great research on this as there are some discussions on 2fa support (I didn't tried yet myself): https://bsky.app/profile/notwes.bsky.social/post/3lwgx6llchc2o.

**Comment by RafaelGSS** [comment]
> I just tested this and it works great.
> 
> What could be a rollout plan?

What do you mean? Wouldn't it be a simple bump of patch version and trigger the workflow again?

**Comment by RafaelGSS** [comment]
By the way, I'm about to test it in https://github.com/nodejs/is-my-node-vulnerable/pull/37

**Comment by mcollina** [comment]
> What do you mean? Wouldn't it be a simple bump of patch version and trigger the workflow again?

This org contains 50+ repositories/modules. Standardizing the release workflow would be necessary, as would some work on NPM to make the links.

@Fdawgs has some way for massively doing edits.

**Comment by RafaelGSS** [comment]
I might be missing some context here, so please correct me if I'm wrong @mcollina.

But I have been using https://github.com/googleapis/release-please-action, and it works very well. The workflow works great in a more scalable org (50+ modules). What do you think about adding support to trusted-packages to this action?

**Comment by mcollina** [comment]
It probably boils down to me and probably everybody in the org _hate_ conventional commits.

**Comment by RafaelGSS** [comment]
Right, so let's define what we would like:

* Automatically create a release PR when:
  * Running an action manually (`workflow_dispatch`) or
  * Whenever a commit lands on `main`
 
* On a remote tag is pushed push the package to npm with provenance enabled. 
  * Each repository should have a `publish.yml` and be synced with npmjs.com just once. 

* Action `workflow_dispatch` to land a `semver-patch` release, reverting the last release if needed (?)

What else?

**Comment by metcoder95** [comment]
>Whenever a commit lands on main

I'd like to suggest to not to this, in my experience, this usually doesn't end well.

>Action workflow_dispatch to land a semver-patch release, reverting the last release if needed 

This can be convenient.

**Comment by Fdawgs** [comment]
I'm happy to pick this up.
My idea for this would be to have a shared workflow over in [fastify/workflows](https://github.com/fastify/workflows ) and would be similar to [fastify/workflows/blob/main/.github/workflows/release.yml ](https://github.com/fastify/workflows/blob/main/.github/workflows/release.yml) but obviously with additional npm publish steps. nearform-actions/optic-release-automation-action does all the incrementing of versions and release notes as seen with https://github.com/fastify/workflows/pull/165

**Comment by RafaelGSS** [comment]
> My idea for this would be to have a shared workflow over in [fastify/workflows](https://github.com/fastify/workflows) and would be similar to fastify/workflows/blob/main/.github/workflows/release.yml

The main difference is that we won't need OTP code anymore. We just need to link the repository/workflow to NPM directly.

**Comment by Fdawgs** [comment]
> > My idea for this would be to have a shared workflow over in [fastify/workflows](https://github.com/fastify/workflows) and would be similar to fastify/workflows/blob/main/.github/workflows/release.yml
> 
> The main difference is that we won't need OTP code anymore. We just need to link the repository/workflow to NPM directly.

I know, but we still need a release workflow!

**Comment by mcollina** [comment]
This combo is what I have for undici https://github.com/nodejs/undici/blob/main/.github/workflows/release-create-pr.yml https://github.com/nodejs/undici/blob/main/.github/workflows/release.yml

**Comment by RafaelGSS** [comment]
> This combo is what I have for undici https://github.com/nodejs/undici/blob/main/.github/workflows/release-create-pr.yml https://github.com/nodejs/undici/blob/main/.github/workflows/release.yml

Yes, that's my suggestion in https://github.com/fastify/fastify/issues/5984#issuecomment-3202060909

> Automatically create a release PR when:
>   * Running an action manually (workflow_dispatch) or

and in 

> On a remote tag is pushed push the package to npm with provenance enabled.
>  * Each repository should have a publish.yml and be synced with npmjs.com just once. 

The undici/release.yml is the `publish.yml` I mentioned. Exactly the same as I suggested. But I don't know if we want to stick to optic-release-automation-action.

**Comment by jsumners** [comment]
> I'd like to suggest to not to this,

Agreed.

**Comment by Uzlopak** [comment]
This was my general release workflow. Basically listening to the release event. Only annoyance was that after the release I added a commit to add the correct version into the package.json. Then I needed to delete the version tag and retag the commit with the new package.json as the version tag and in the persisted sourcecode zip in the release page the package.json had the state before the retagging. 

```yml
name: Release
on:
  workflow_call:
    inputs:
      version:
        description: 'Version'
        required: false
        type: string
      branch:
        description: 'branch'
        required: true
        type: string
        default: master
      git-tag:
        description: 'git tag'
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Version based on input or tag
        id: version
        run: if [ "$VERSION" != "" ]; then echo ::set-output name=version::${VERSION}; else echo ::set-output name=version::${TAG:1}; fi
        env:
          VERSION: ${{ inputs.version }}
          TAG: ${{ inputs.git-tag }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{inputs.branch}}

      - name: Set version in package.json
        run: |
          SEARCH='("version":[[:space:]]*").+(")'
          REPLACE="\1${VERSION}\2"
          sed -i -E "s/${SEARCH}/${REPLACE}/g" package.json
        env:
          VERSION: ${{ steps.version.outputs.version}}

      - name: Commit and Push Changes
        if: ${{ inputs.git-tag != '' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./package.json
          git commit -m "Release ${VERSION}"
          git push origin HEAD:${BRANCH}
        env:
          VERSION: ${{ steps.version.outputs.version}}
          BRANCH: ${{inputs.branch}}

      - name: Update tag
        if: ${{ inputs.git-tag }}
        run: git tag -f ${TAG}
        env:
          TAG: ${{inputs.git-tag}}
```

And then it was used in the repo like this:

```yml
name: Release
on:
  release:
    types:
      - released
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write

jobs:
  publish:
    uses: cthulhu-oidc/workflows/.github/workflows/release.yml@master
    with:
      git-tag: ${{ github.event.release.tag_name }}
      branch:  ${{ github.event.release.target_commitish }}
    secrets: inherit
```
